---

- hosts: all
  become: true
  pre_tasks:

  - name: Update Amazone Linux
    tags: always 
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon Linux"

  - name: Update Ubuntu
    tags: always
    yum:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache for Amazone Linux
    tags: apache,centos
    yum:
      name:
        - httpd
        - php
      state: latest

  - name: copy default html file for site
    tags: apache
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:      

   - name: install MariaDB for Ubuntu
     tags: mariadb,ubuntu
     apt:
       name:
         - mariadb-server
       state: latest

...       
