---

- hosts: all
  become: true
  pre_tasks:

  - name: Update Amazone Linux
    tags: always 
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: Update Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache for Amazone Linux
    tags: apache,centos
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: start httpd (Amazon Linux)
    tags: apache,centos
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Amazon"

  - name: change httpd.conf
    tags: apache,centos
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin mail@domain.com
    when: ansible_distribution == "Amazon"
    register: apache_mark

  - name: restart httpd (AmazonOS)
    tags: apache,centos
    service:
      name: httpd
      state: restarted
    when: apache_mark.changed

  - name: copy default html file for site
    tags: apache
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:      

   - name: install MariaDB for Ubuntu
     tags: mariadb,ubuntu
     apt:
       name:
         - mariadb-server
       state: latest

- hosts: workstation
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: all
  become: true
  tasks:

  - name: create luka user
    tags: always
    user:
            name: luka
            group: root

  - name: add ssh key for luka
    tags: always
    authorized_key:
            user: luka
            key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFGEDUsGiAaXz8EjFgXRAXqEf/T3SxemOKAvf5jo9Y22 Ansible"

  - name: add sudoers file for luka
    tags: always
    copy:
            src: sudoer_luka
            dest: /etc/sudoers.d/simone
            owner: root
            group: root

...       
